### ISSUE TITLE
É possível utilizar o Git no Windows?

### ISSUE THREAD

**Issue by elainemeloti** [fernandomayer/git-rautu#1]
O Git funciona bem no Windows?

**Comment by fernandomayer** [comment]
@elainemeloti sinceramente eu não posso te responder essa pergunta pois não uso Windows.

Mas conheço algumas pessoas que usam e parece que o git funciona da mesma forma que no Linux. A maioria usa o [Git for Windows](http://msysgit.github.io/), que simula um terminal bash do Linux, e portanto os comandos são os mesmos apresentados nesse tutorial.

**Comment by fnk0c** [comment]
Pode utilzar o [Cygwin](https://www.cygwin.com/) para emular um terminal linux e a partir dele, instalar o git e utilizar normalmente. Nunca fiz, pois não utilizo Windows também, porém ja ví pessoal fazendo isso.

**Comment by elainemeloti** [comment]
Muito obrigada pelas respostas!

O que eu ouvi falar em uma palestra esses dias é que podem acontecer alguns bugs pelos sistemas operacionais serem diferentes... no caso, o do servidor do Git ser Linux...e o do meu computador Windows... será que utilizando uma máquina virtual com Linux resolve? 
Estou pensando em instalar mais um sistema operacional aqui na minha máquina, ela só está precisando de um upgrade... rsrsrsrs

**Comment by fnk0c** [comment]
Desconheço destes bugs. Faça dual boot.

**Comment by fernandomayer** [comment]
Eu também aconselharia fazer dual boot ao invés de usar máquina virtual. E com o tempo migre para o Linux -- sua vida vai mudar para melhor ;)

**Comment by elainemeloti** [comment]
Dual boot me parece a melhor solução também!!! Muito obrigada pelas dicas!!!
